AllCops:
  Exclude:
    - vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 360
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

# dealbreaker:
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SymbolArray:
  Enabled: false

# we still support ruby 1.8
Style/HashSyntax:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: true
Style/RegexpLiteral:
  Enabled: true
Style/WordArray:
  Enabled: true

# this catches the cases of using `module` for parser functions, types, or
# providers
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
